CREATE TABLE TBL_USUARIO
(
    ID_USUARIO SERIAL PRIMARY KEY,
    TX_NOME    VARCHAR(50)  NOT NULL,
    TX_LOGIN   VARCHAR(40)  NOT NULL,
    TX_SENHA   VARCHAR(200) NOT NULL,
    TX_ROLE    VARCHAR(10)   NOT NULL
);