CREATE TABLE TBL_POSTAGEM
(
    ID_POSTAGEM  SERIAL PRIMARY KEY,
    TX_TITULO    VARCHAR(50) NOT NULL,
    TX_CONTEUDO  VARCHAR(500),
    DT_CRIACAO   TIMESTAMP(6),
    ID_AUTOR     INTEGER,
    FOREIGN KEY (ID_AUTOR) REFERENCES TBL_USUARIO (ID_USUARIO)
);
