CREATE TABLE TBL_COMENTARIO
(
    ID_COMENTARIO SERIAL PRIMARY KEY,
    TX_CONTEUDO   VARCHAR(100) NOT NULL,
    DT_CRIACAO    TIMESTAMP(6) NOT NULL,
    ID_POSTAGEM   INTEGER       NOT NULL,
    ID_AUTOR      INTEGER,
    FOREIGN KEY (ID_POSTAGEM) REFERENCES TBL_POSTAGEM (ID_POSTAGEM),
    FOREIGN KEY (ID_AUTOR) REFERENCES TBL_USUARIO (ID_USUARIO)
);